name: Fetch Google Trends Feed

on:
  schedule:
    - cron: "*/30 * * * *" # Menjalankan setiap 30 menit
  workflow_dispatch: # Memungkinkan menjalankan secara manual

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Fetch Google Trends RSS Feed
      run: |
        # Format nama folder dan file
        FOLDER_NAME=$(date +'%d_%m_%Y')
        FILE_NAME=$(date +'%S-%M-%H').xml

        # Buat folder feeds/hari_bulan_tahun jika belum ada
        mkdir -p feeds/$FOLDER_NAME

        # Download data dari URL dan simpan ke file
        curl -o feeds/$FOLDER_NAME/$FILE_NAME "https://trends.google.co.id/trending/rss?geo=ID"

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add feeds/
        git commit -m "Add Google Trends feed $(date +'%S-%M-%H_%d-%m-%Y') [ci skip]" || echo "No changes to commit"
        git push
